### PR TITLE
Updates Dockerfile to use debian wheezy

### PR DESCRIPTION
**Pull request by rolandpoulter**
Replaces `apk` commands with `apt-get`

### CODE REVIEW

**Comment by rolandpoulter** [comment]
This PR requires changes to `on-tasks` and `on-core` Dockerfile.
https://github.com/RackHD/on-tasks/pull/336
https://github.com/RackHD/on-core/pull/210

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by pscharla** [comment]
:+1:

**Comment by pscharla** [comment]
@RackHD/corecommitters This one looks ready to merge

**Pull request merged**
