### PR TITLE
Add UEFI support to CoreOS installer (CoreOS Issue #1239)

### PR DESCRIPTION
**Pull request by tgelter**

### CODE REVIEW

**Comment by tgelter** [comment]
https://github.com/coreos/bugs/issues/1239

**Comment by michaelsteven** [comment]
related support ticket https://rackhd.atlassian.net/browse/RAC-6471

**Comment by RackHDCI** [comment]
The Copyright Check has failed!
The files listed below do not have a valid copyright statement:
- data/profiles/install-coreos.ipxe

**Comment by keedya** [comment]
@tannoa2 @geoff-reid can u review this change

**Comment by keedya** [comment]
@king-jam can u review this one?

**Comment by tgelter** [comment]
Thanks @keedya / @king-jam / @michaelsteven !

**Pull request merged**
