### PR TITLE
Feature/use init for startup

### PR DESCRIPTION
**Pull request by davidzuhn**
Ubuntu 16.04 uses systemd, which has a compability mode for init scripts and not for upstart.   This patch contains a rudimentary init script (start only, matching the capabilities of the upstart script) and works on Ubuntu 14.04 *and* Ubuntu 16.04.

.gitignore has been updated to reflect the .xz files created on Ubuntu 16.

### CODE REVIEW

**Comment by davidzuhn** [comment]
test this please

**Comment by anhou** [comment]
:+1:

**Comment by anhou** [comment]
test this please

**Comment by davidzuhn** [comment]
@RackHD/corecommitters  please review

**Comment by benbp** [comment]
FYI @zhangy42, since I believe you're working on systemd scripts for CentOS.

**Comment by zhangy42** [comment]
I am working on researching how to deploy monorail on CentOS, and as a result, there will be a list of works to do for a decent deploy. There will definitely have one item in the list that is about writing systemd scripts/configuration file.

**Comment by davidzuhn** [comment]
Depending on your desired CentOS target version, you may be better off using the init compatibility there as well, at least for the time being.  I suspect there's little else within RackHD that would require CentOS 7, and being able to support both 6 and 7 could be useful.

**Pull request merged**
