### PR TITLE
remove the views from on-taskgraph

### PR DESCRIPTION
**Pull request by tannoa2**
In the stand alone WFE, we are not loading the views. I removed them from the Swagger yaml file to fix the issue

### CODE REVIEW

**Comment by tannoa2** [comment]
@RackHD/veyron

**Comment by keedya** [comment]
The Copyright Check has failed!
The files listed below do not have a valid copyright statement:
- api/swagger.json

**Comment by tannoa2** [comment]
test this please

**Comment by tannoa2** [comment]
HI @geoff-reid the copy right comment in the swagger json is casuing issues.`-> /api/rpc/index.js:87

API Errors:

  #: Additional properties not allowed: //

1 error and 0 warnings

`

**Comment by keedya** [comment]
The Copyright Check has failed!
The files listed below do not have a valid copyright statement:
- api/swagger.json

**Comment by keedya** [comment]
The Copyright Check has failed!
The files listed below do not have a valid copyright statement:
- api/swagger.json

**Pull request merged**
