### PR TITLE
Reverting a chance that was made during the Centos install validation…

### PR DESCRIPTION
**Pull request by tannoa2**
…. The issue is fixed by centos.rackhdcallback

### CODE REVIEW

**Comment by tannoa2** [comment]
@keedya @anhou @yyscamper @amymullins @jlongever @uppalk1 @zyoung51

**Comment by keedya** [comment]
:+1:

**Comment by heckj** [comment]
:+1:

**Comment by tannoa2** [comment]
test this please

**Comment by anhou** [comment]
test this please

**Comment by yyscamper** [comment]
:+1:

**Pull request merged**
