### PR TITLE
deb package creation and dependency based on node 4

### PR DESCRIPTION
**Pull request by anhou**
based on PR https://github.com/RackHD/docs/pull/286,

@RackHD/corecommitters @benbp @jlongever @heckj

### CODE REVIEW

**Comment by yyscamper** [comment]
jenkins: test this please

**Comment by benbp** [comment]
:+1:

**Comment by anhou** [comment]
test this please

**Comment by anhou** [comment]
test this please

**Comment by yyscamper** [comment]
:+1:

**Pull request merged**
