### PR TITLE
Add Redfish Chassis poller graph

### PR DESCRIPTION
**Pull request by jlongever**
Adds create chassis poller graph.

@RackHD/corecommitters @zyoung51 @uppalk1 @tannoa2 @keedya 

For PR https://github.com/RackHD/on-tasks/pull/139

### CODE REVIEW

**Comment by zyoung51** [comment]
+1

**Comment by jlongever** [comment]
unit test failure requires PR https://github.com/RackHD/on-tasks/pull/139

**Comment by yyscamper** [comment]
:+1:

**Comment by jlongever** [comment]
test this please

**Pull request merged**
