### PR TITLE
updated switch discovery to update lookups

### PR DESCRIPTION
**Pull request by VulpesArtificem**
for https://github.com/RackHD/RackHD/issues/236
@RackHD/corecommitters @johren 
adds a task to the switch discovery workflow to add all of the switch's interface mac addresses to the lookups collection

depends on https://github.com/RackHD/on-tasks/pull/219

### CODE REVIEW

**Comment by benbp** [comment]
👍

**Comment by yyscamper** [comment]
:+1:

**Comment by benbp** [comment]
test this please

**Comment by benbp** [comment]
test this please

**Comment by yyscamper** [comment]
Jenkins: test this please

**Pull request merged**
