### PR TITLE
Specify version 1.8.13-1 for ipmitool package

### PR DESCRIPTION
**Pull request by johren**
Trying this again, hopefully with all of the dependencies this time.  For ODR-352.

This depends on https://eos2git.cec.lab.emc.com/OnRack/onrack-base/pull/2

DO NOT MERGE until both of these PRs are ready.

### CODE REVIEW

**Comment by johren** [comment]
@RackHD/corecommitters

**Comment by johren** [comment]
@stuart-stanley @derrickostertag

**Comment by derrickostertag** [comment]
+1

**Comment by johren** [comment]
Is it safe to ignore the coverage failure?  It looks like it decreased by 0%???

**Comment by jlongever** [comment]
@johren I think it's OK to ignore,  it's really a no change in coverage but coveralls marks it failed.

**Comment by jlongever** [comment]
+1

**Comment by johren** [comment]
Looks like I have two +1s and the onrack-base PR is also ready.
@RackHD/corecommitters please merge when ready and poke me so I can merge the onrack-base PR at approx. the same time.

**Pull request merged**
