### PR TITLE
Added functional test for /notifications &  /workflows

### PR DESCRIPTION
**Pull request by tannoa2**
Signed-off-by: Anitha Srinivasan <anitha.srinivasan@dell.com>

### CODE REVIEW

**Comment by RackHDCI** [comment]
The Copyright Check has failed!
The files listed below do not have a valid copyright statement:
- .gitignore - api/swagger.json

**Comment by keedya** [comment]
The Copyright Check has failed!
The files listed below do not have a valid copyright statement:
- .gitignore - api/swagger.json

**Comment by RackHDCI** [comment]
The Copyright Check has failed!
The files listed below do not have a valid copyright statement:
- .gitignore - api/swagger.json

**Comment by keedya** [comment]
The Copyright Check has failed!
The files listed below do not have a valid copyright statement:
- .gitignore - api/swagger.json

**Pull request merged**
