### PR TITLE
[1.2] updated switch discovery to update lookups

### PR DESCRIPTION
**Pull request by VulpesArtificem**
for RackHD/RackHD#236
@RackHD/corecommitters @johren 
adds a task to the switch discovery workflow to add all of the switch's interface mac addresses to the lookups collection

depends on https://github.com/RackHD/on-tasks/pull/220

### CODE REVIEW

**Comment by yyscamper** [comment]
:+1:

**Comment by benbp** [comment]
👍

**Comment by johren** [comment]
Release has been cut.  This can now go in for next release.  Go ahead and merge when ready.

**Comment by johren** [comment]
@RackHD/corecommitters

**Pull request merged**
