### PR TITLE
Add workflow to clear drive partition

### PR DESCRIPTION
**Pull request by yyscamper**
This PR is to implement a workflow to clear all partition for target drives.

It is a sub-feature of ORFS-97 [Extend base OS and workflow to configure RAID array prior to bootstrap](https://hardware.corp.emc.com/display/CI/Extend+base+OS+and+workflow+to+configure+RAID+array+prior+to+bootstrap).

This workflow will be eventually embedded in OS bootstrap workflow, as we found some error when install ESXi and Redhat alternately, if the drive partition is corrupted, the ESXi installation will fail, so we have to manually reset the drive config. So if this workflow is inserted, we can avoid such manual work.

The drive partition operation will depend on a tool named "parted", @iceiilin opened another PR (https://github.com/RackHD/on-imagebuilder/pull/7) to include this tool in our micorkernel.

@RackHD/corecommitters @iceiilin @WangWinson @pengz1 @sunnyqianzhang @zyoung51 

The dependent PRs: 
 - https://github.com/RackHD/on-imagebuilder/pull/7
 - https://github.com/RackHD/on-tasks/pull/71

### CODE REVIEW

**Comment by yyscamper** [comment]
This PR https://github.com/RackHD/on-tasks/pull/71 need be merged first to ensure the travis-ci build passes.

**Comment by benbp** [comment]
:+1:

**Comment by benbp** [comment]
This workflow should probably terminate with a shell reboot task or something?

**Comment by yyscamper** [comment]
@benbp , sure, I will add it.

**Comment by yyscamper** [comment]
Close this PR, as base on our design for ORFS-97, we can move the clear-partition work to kickstart file.

**Pull request closed without merging**
