### PR TITLE
Fix bug that created duplicate service graph instances

### PR DESCRIPTION
**Pull request by benbp**
Fixes https://github.com/RackHD/RackHD/issues/371

@RackHD/corecommitters @VulpesArtificem @rolandpoulter

### CODE REVIEW

**Comment by VulpesArtificem** [comment]
👍

**Comment by heckj** [comment]
:+1:

**Comment by yyscamper** [comment]
:+1:

**Comment by yyscamper** [comment]
test this please

**Comment by anhou** [comment]
:+1:

**Comment by anhou** [comment]
test this please

**Pull request merged**
