### PR TITLE
Replace bootstrap ubuntu with rancherOS in discovery and Micro-docker

### PR DESCRIPTION
**Pull request by keedya**
- Allow us to use micro docker image in the active
  discovery on compute nodes

### CODE REVIEW

**Comment by keedya** [comment]
Update Static file services job in jenkins to include rancherOS kernel and initrd images
test this please

**Comment by keedya** [comment]
This PR depends on https://github.com/RackHD/RackHD/pull/656
to make sure we don't break the docker build

**Comment by keedya** [comment]
@RackHD/corecommitters @geoff-reid @tannoa2 @uppalk1

**Comment by yyscamper** [comment]
@keedya : The PR code itself is OK, but we need a lot doc be ready before merging:
- The doc about source code installation and npm installation only specify to download the legacy microkernel files, the ranchor OS related files need be added.
- Some CI build and release script need be updated to make sure the ranchOS files are installed corrected.
- Some instruction need be created about how to play with RanchOS microkernel if there is anything that different with before, for example, how to create overlay, how to debug in microkernel. 
- The community need be notified so as not bring surprise to them.

**Comment by yyscamper** [comment]
Add Build&Release team for awareness: @panpan0000 @PengTian0 @changev

**Comment by keedya** [comment]
@yyscamper thanks for your input:

I agree that we need to document and notify the community about these changes

- Ci concerns: 
the smoke tests are passing and that is because I updated all CI jobs related
Bintray now has all the images in it
- Finally, RancherOS is an open source and their documentation covers all the info needed. I will add links in rackhd docs for it

Thanks
Andre

**Comment by yyscamper** [comment]
Hello @keedya : 

Today, @PengTian0 help to review your code, I think most code are ready, only left some doc and test concern:

(1)  The doc about [Ubuntu Package Installation](http://rackhd.readthedocs.io/en/latest/rackhd/ubuntu_package_installation.html)  and [Npm Based Installation](http://rackhd.readthedocs.io/en/latest/rackhd/npm_based_installation.html) hard code the static files that need to download, so the ranchOS related static files need be added.

(2) I am not sure whether you have tested the on-imagebuilder debian package, and the ova/vagrant box/docker build (Though your code looks enough now) because I don't want to bring any last-minute problems for the next sprint release. 

(3) I am not sure whether the existing overlayfs can be used or not, if not, whether you have built a new overlayfs that includes those tools such as percli, secure erase tools. This item is not immediate now as your change doesn't remove the legacy bootstrap Ubuntu, but as time goes on, we need to switch all into new microkernel.

**Comment by keedya** [comment]
@yyscamper bootstrap ubuntu is still used for workflows like secure erase. I figured we can tackle the rest of the workflows that relies on bootstrap in a different story(baby steps) 😊

**Comment by keedya** [comment]
For testing, I have a private Jenkins job running smoke test periodically since Friday to ensure consistency

**Comment by yyscamper** [comment]
@keedya : I agree with moving the overlayfs related problem into another story.

For testing, my concern is that smoke-test is not enough, since debian package/ova/vagrant/docker build will all download the static files, if we can have a pilot run for them, then we will not fall into trouble about those last minute bug before sprint release.

I will talk with @PengTian0 tomorrow, whether we can run the build testing on your private branch, if this is difficult, I'm OK to merge your PR first, but trigger the build testing immediately (not follow the regular build release testing timeline). 

Could you please open a PR for the doc change to make sure everything is ready?

**Comment by geoff-reid** [comment]
@PengTian0 @yyscamper @keedya 
Any update with running the build testing on Andre's private branch?

**Comment by keedya** [comment]
depends on on-imagebuilder :https://github.com/RackHD/on-imagebuilder/pull/79

**Comment by yyscamper** [comment]
@keedya @geoff-reid : I have pinged @PengTian0, she will setup and run the build testing after she finishes her ongoing urgent task. I hope you will not be hurry to merge this feature.

**Comment by PengTian0** [comment]
@keedya I created a private job to run "[MasterCI](http://rackhdci.lss.emc.com/job/Experimental-Jobs/job/MasterCI)" 
It can accept a manifest url and build package and images according to the manifest file.

**Comment by PengTian0** [comment]
👍 The private jenkins build passed!

**Pull request merged**
