### PR TITLE
Fixed the logging issue with Arista switches

### PR DESCRIPTION
**Pull request by tannoa2**
Please enter the commit message for your changes. Lines starting

### CODE REVIEW

**Comment by tannoa2** [comment]
@RackHD/committers @RackHD/veyron @larry-dean @jgolio 
This PR:
- Fixes the logging issue with Arista switches 
- Adds support for remote syslog so the switch errors will show up in Rackhd log as well so the user wouldn't have to check the switch logs

**Comment by johren** [comment]
Has this been tested with Cisco and Brocade also?   The code here appears to touch all of these code paths in taskrunner.py.

**Comment by tannoa2** [comment]
@johren This change has been tested with Arista only. @larry-dean has been tagged here since he has dealt with Cisco and Brocade switches.

**Comment by keedya** [comment]
@johren there is no changes here related to Brocade or cisco. @tannoa2 changes are dynamically rendered based on switch vendor in get profile/switch/{vendor} api. There is no impact on the original code and the support for cisco or Brocade

**Comment by johren** [comment]
I don't see how this does not affect  the Cisco or Brocade code path with these code changes:

+                                if(taskgraphInstance.injectableName === "Graph.Switch.Discovery.Arista.Ztp"){
 +                                    switchVendor = "arista";
 +                                }else if(taskgraphInstance.injectableName === "Graph.Switch.Discovery.Brocade.Ztp"){
 +                                    switchVendor = "brocade";                                    
 +                                }else if(taskgraphInstance.injectableName === "Graph.Switch.Discovery.Cisco.Poap"){
 +                                    switchVendor = "cisco";
 +                                }

**Comment by keedya** [comment]
👍

**Comment by tannoa2** [comment]
@johren Tested with  Cisco and it works as well. 
Attached are the logs that shows  successful ZTP/POAP  for Arista and Cisco. Both vendors discovered,  and cataloged successfully. 

I started to look into Brocade, and it seems to me that we don't have full support for it.  I couldn't find the DAD file https://github.com/RackHD/on-dhcp-proxy/blob/master/dhcpd.conf#L46 anywhere.

@larry-dean where can I get the brcd.conf ?

**Comment by tannoa2** [comment]
[Arista_workflowSucess.txt](https://github.com/RackHD/on-taskgraph/files/1377263/Arista_workflowSucess.txt)
[cisco_Catalogs.txt](https://github.com/RackHD/on-taskgraph/files/1377264/cisco_Catalogs.txt)
[Cisco_node.txt](https://github.com/RackHD/on-taskgraph/files/1377265/Cisco_node.txt)
[cisco_workflow_success.txt](https://github.com/RackHD/on-taskgraph/files/1377266/cisco_workflow_success.txt)
[Arista_Catalogs.txt](https://github.com/RackHD/on-taskgraph/files/1377267/Arista_Catalogs.txt)
[Arista_node.txt](https://github.com/RackHD/on-taskgraph/files/1377268/Arista_node.txt)

**Comment by johren** [comment]
Approving without testing of the Brocade switch because we do not appear to have all files necessary for testing.

@tannoa2 could you comment which Cisco and Arista switch model and which software (e.g. IOS) versions you tested in case we need to come back to this in the future?

**Comment by tannoa2** [comment]
@johren 
Cisco info:
``` {
        "id": "36ffbf01-7bc2-4e83-8fae-f2ca21c36a68",
        "node": "/api/2.0/nodes/59de6d3b0f1ecc070f023eb8",
        "source": "version",
        "data": {
            "kern_uptm_secs": "59",
            "kick_file_name": "bootflash:///I5.1.bin",
            "rr_service": null,
            "slot0_size": "0",
            "kick_tmstmp": "10/29/2016 13:46:41",
            "bios_cmpl_time": "12/05/2016",
            "bootflash_size": "1838592",
            "kickstart_ver_str": "7.0(3)I5(1)",
            "kick_cmpl_time": "10/29/2016 6:00:00",
            "chassis_id": "Nexus 3172T Chassis",
            "proc_board_id": "FOC20043A4K",
            "memory": "4031560",
            "manufacturer": "Cisco Systems, Inc.",
            "kern_uptm_mins": "3",
            "bios_ver_str": "4.0.0",
            "cpu_name": "Intel(R) Pentium(R) CPU  @ 2.00GHz",
            "kern_uptm_hrs": "0",
            "rr_usecs": "13776",
            "rr_sys_ver": "7.0(3)I5(1)",
            "rr_reason": "Reset Requested by CLI command reload",
            "rr_ctime": "Wed Oct 11 19:34:14 2017",
            "header_str": "Cisco Nexus Operating System (NX-OS) Software\nTAC support: http://www.cisco.com/tac\nCopyright (C) 2002-2016, Cisco and/or its affiliates.\nAll rights reserved.\nThe copyrights to certain works contained in this software are\nowned by other third parties and used and distributed under their own\nlicenses, such as open source.  This software is provided as is and unless\notherwise stated, there is no warranty, express or implied, including but not\nlimited to warranties of merchantability and fitness for a particular purpose.\nCertain components of this software are licensed under\nthe GNU General Public License (GPL) version 2.0 or \nGNU General Public License (GPL) version 3.0  or the GNU\nLesser General Public License (LGPL) Version 2.1 or \nLesser General Public License (LGPL) Version 2.0. \nA copy of each such license is available at\nhttp://www.opensource.org/licenses/gpl-2.0.php and\nhttp://opensource.org/licenses/gpl-3.0.html and\nhttp://www.opensource.org/licenses/lgpl-2.1.php and\nhttp://www.gnu.org/licenses/old-licenses/library.txt.",
            "host_name": "switch",
            "mem_type": "kB",
            "kern_uptm_days": "0"
        }
    }
]```
Arista Info:
```{
        "id": "5941f6fe-d568-43d6-88a9-0efd6566e559",
        "node": "/api/2.0/nodes/59d798662665cd6d6c1a2204",
        "source": "version",
        "data": {
            "Hardwaremodel": "AristaDCS-7048T-A-R",
            "Hardwareversion": "01.07",
            "Serialnumber": "JPE15273830",
            "SystemMACaddress": "001c.73d9.54b1",
            "Softwareimageversion": "4.9.8.1",
            "Architecture": "i386",
            "Internalbuildversion": "4.9.8.1-1271700.EOS498",
            "InternalbuildID": "db78ef10-50a8-40a5-8ec1-6f8175378f02",
            "Uptime": "2minutes",
            "Totalmemory": "4037980kB",
            "Freememory": "2642512kB"
        }
    }
````

**Comment by tannoa2** [comment]
Arista Info:
```{
        "id": "5941f6fe-d568-43d6-88a9-0efd6566e559",
        "node": "/api/2.0/nodes/59d798662665cd6d6c1a2204",
        "source": "version",
        "data": {
            "Hardwaremodel": "AristaDCS-7048T-A-R",
            "Hardwareversion": "01.07",
            "Serialnumber": "JPE15273830",
            "SystemMACaddress": "001c.73d9.54b1",
            "Softwareimageversion": "4.9.8.1",
            "Architecture": "i386",
            "Internalbuildversion": "4.9.8.1-1271700.EOS498",
            "InternalbuildID": "db78ef10-50a8-40a5-8ec1-6f8175378f02",
            "Uptime": "2minutes",
            "Totalmemory": "4037980kB",
            "Freememory": "2642512kB"
        }
    }
````

**Pull request merged**
