### PR TITLE
support install-windows graph schema, allow unit-test passes

### PR DESCRIPTION
**Pull request by yyscamper**
Actually this file change is just want to make this unit-test ( https://github.com/yyscamper/on-taskgraph/blob/master/spec/lib/graph-library-spec.js#L50 ) happy after task-schema refactor, in the long run, this unit-test need be refactored as well.

@RackHD/corecommitters @iceiilin @cgx027 @pengz1 @lanchongyizu @tannoa2 @amymullins 

jenkins: depends on https://github.com/RackHD/on-core/pull/217, https://github.com/RackHD/on-tasks/pull/360

### CODE REVIEW

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by changev** [comment]
test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by changev** [comment]
test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by changev** [comment]
test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by yyscamper** [comment]
test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by changev** [comment]
test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by changev** [comment]
test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by changev** [comment]
test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by PengTian0** [comment]
test this please

**Comment by iceiilin** [comment]
+1

**Comment by yyscamper** [comment]
jenkins: test this please

**Pull request merged**
