### PR TITLE
[RAC-6753]Correct several taskgraph's friendlyName

### PR DESCRIPTION
**Pull request by leoyjchang**
*Background*
It has been found during web ui development that some graphs have extra space in their friendlyname. After further screening, I also found some typo in some graph's friendlyname.  This is not a good style and we need to fix them all.

@lanchongyizu @pengz1 @yaolingling @iceiilin @mcgG @AlaricChan

### CODE REVIEW

**Comment by pengz1** [comment]
@Leo, there are some other graphs have the same friendly name, is this inside your scope?
Like rancher-discovery-graph.js vs  discovery-graph.js

**Comment by leoyjchang** [comment]
@pengz1 Good point. I intended to cover duplicated friendlyname case but still miss some. I will update the PR for the case you mentioned.

**Comment by pengz1** [comment]
A simple tip for you, you can use web-ui for name sorting...

**Comment by pengz1** [comment]
Here is the web-ui demo link: http://10.62.59.160:8081

**Comment by RackHDCI** [comment]
The Copyright Check has failed!
The files listed below do not have a valid copyright statement:
- lib/graphs/brocade-switch-discovery-graph.js

**Pull request merged**
