### PR TITLE
RAC-4884: Add scheduler.proto into deb

### PR DESCRIPTION
**Pull request by panpan0000**
Detail in https://rackhd.atlassian.net/browse/RAC-4884
on-taskgraph deb can't start

Thanks to @lanchongyizu 

Reviewer: 

@brianparry  @changev @yyscamper  @anhou  @PengTian0  @lanchongyizu

### CODE REVIEW

**Comment by changev** [comment]
:+1:

**Comment by PengTian0** [comment]
:+1:

**Comment by lanchongyizu** [comment]
I found that `static` is also required for swagger.

**Comment by panpan0000** [comment]
@lanchongyizu . thank you , I added it also.

**Pull request merged**
