### PR TITLE
ODR-547 Updated discovery-refresh-graphs.js to use sku discovery

### PR DESCRIPTION
**Pull request by jimturnquist**
Updated discovery-refresh-graphs.js to use sku discovery tasks instead of just discovery.

### CODE REVIEW

**Comment by heckj** [comment]
If you run this with pollers already existing, will it create another set of pollers?

**Comment by benbp** [comment]
I believe it will: https://github.com/RackHD/on-tasks/blob/master/lib/jobs/create-default-pollers.js#L68-L75

**Comment by jimturnquist** [comment]
@Ben:   Would it be possible to test if pollers are already enabled and just skip that.  If a discovery-refresh-graph is in play, it really can't assume where the previous discovery stopped short.  Any thoughts?

**Comment by benbp** [comment]
@jimturnquist yeah, the easiest way to me seems to be updating the workitems.find call to the database to be a workitems.findOrCreate call (see https://github.com/RackHD/on-tasks/blob/master/lib/jobs/create-default-pollers.js#L74).

Some example usage of findOrCreate: https://github.com/RackHD/on-core/blob/ea389bb25bdd6c890880442730481d78ac6ad052/lib/services/environment.js#L32-L35

Basically, `findOrCreate(query, document)`. You'd want the query to include the config in the query I believe (i.e. `query = { node: self.nodeId, config: { command: <cmd> } }`), since it gets called multiple times as it iterates through the poller options.

**Comment by jimturnquist** [comment]
Thanks Ben.

**Comment by jimturnquist** [comment]
@benbp @heckj I was able to make the on-tasks changes suggested by Ben to use findOrCreate.  Tests have been updated as well.

**Comment by yyscamper** [comment]
:+1:

**Comment by johren** [comment]
@RackHD/corecommitters

**Comment by jlongever** [comment]
test this please

**Comment by jlongever** [comment]
^^ ignorable smoke test failures.
+1

**Pull request merged**
