### PR TITLE
Add an index for mongo graphobjects.instanceId

### PR DESCRIPTION
**Pull request by benbp**
Given this is our primary lookup field, we should probably index it.

@RackHD/corecommitters @VulpesArtificem @pscharla @zyoung51 @jlongever

### CODE REVIEW

**Comment by yyscamper** [comment]
:+1:

**Comment by benbp** [comment]
Closing in favor of https://github.com/RackHD/on-core/pull/207 (hat tip to @vulpesartficiem)

**Comment by benbp** [comment]
Closing in favor of https://github.com/RackHD/on-core/pull/207 (hat tip to @vulpesartficiem)

**Comment by benbp** [comment]
Re-opening because of https://github.com/RackHD/on-core/pull/207#issuecomment-245373249

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by brianparry** [comment]
:+1:

**Pull request merged**
