### PR TITLE
don't fail graph if ignoreFailure true

### PR DESCRIPTION
**Pull request by VulpesArtificem**
fix for https://github.com/RackHD/RackHD/issues/327

requires
https://github.com/RackHD/on-tasks/pull/344
and
https://github.com/RackHD/on-core/pull/213

@RackHD/corecommitters @pscharla

### CODE REVIEW

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by pscharla** [comment]
@RackHD/corecommitters: please review in the near term. This PR is blocking a couple P1 ODRs

**Comment by yyscamper** [comment]
jenkins: depends on https://github.com/RackHD/on-tasks/pull/344, https://github.com/RackHD/on-core/pull/213

**Comment by yyscamper** [comment]
jenkins: test this please

**Comment by yyscamper** [comment]
jenkins: test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Pull request merged**
