### PR TITLE
add Graph.BootstrapRancher

### PR DESCRIPTION
**Pull request by lanchongyizu**
**Background**

We need Graph.BootstrapRancher for debugging. Please refer to https://rackhd.readthedocs.io/en/latest/rackhd/microkernel.html#how-to-login-microkernel

**Done**

Add Graph.BootstrapRancher

@RackHD/corecommitters @pengz1 @nortonluo

### CODE REVIEW

**Comment by keedya** [comment]
@lanchongyizu have you tested this graph. Would the user be able to ssh into rancher without loading any docker image.

**Comment by markbeierl** [comment]
I have tried this with a manually added graph as follows:

```
 curl -X PUT --header 'Content-Type: application/json' --header 'Accept: text/plain' -d '{
    "friendlyName": "Bootstrap Rancher Microkernel",
    "injectableName": "Graph.BootstrapRancher",
    "options": {
        "bootstrap-rancher": {
            "dockerFile": "secure.erase.docker.tar.xz"
        }
    },
    "tasks": [
        {
            "ignoreFailure": true,
            "label": "set-boot-pxe",
            "taskName": "Task.Obm.Node.PxeBoot"
        },
        {
            "label": "reboot-start",
            "taskName": "Task.Obm.Node.Reboot",
            "waitOn": {
                "set-boot-pxe": "finished"
            }
        },
        {
            "label": "bootstrap-rancher",
            "taskName": "Task.Linux.Bootstrap.Rancher",
            "waitOn": {
                "reboot-start": "succeeded"
            }
        }
    ]
}' http://100.67.22.1:9090/api/common/workflows/graphs
```

While the docker image does start, I cannot ssh to the system.  Port 22 is not listening.  I have also tried adding openssh to the docker image that gets loaded, exposing port 22 and starting sshd, but that also does not allow me to ssh to the running server.

**Comment by lanchongyizu** [comment]
@keedya @markbeierl  This graph loads the default docker image, please refer to https://github.com/RackHD/on-tasks/blob/master/lib/task-data/tasks/bootstrap-rancher.js#L12. But we still can't ssh into RancherOS, since rancher console container where `sshd` exists I think is waiting for `/etc/rc.local` to finish. Rancher developers suggest us to finish `/etc/rc.local` as normal and check the result in another background script.

**Comment by lanchongyizu** [comment]
@keedya @markbeierl I create a PR to fix the issue, please check with https://github.com/RackHD/on-taskgraph/pull/368.

**Pull request merged**
