### PR TITLE
Rename generate-tag graph to match glob load pattern

### PR DESCRIPTION
**Pull request by benbp**
Glob loading looks for `*-graph.js` otherwise this graph won't get loaded.

@zyoung51 @RackHD/corecommitters

### CODE REVIEW

**Comment by heckj** [comment]
:+1: 
Glob loading strikes again!

Maybe we should add a stanza about that in our developer guide? 

(you guys are going to think I'm all docs-crazy, but I'm trying to figure out how to expose these development idioms and conventions in a reasonable way)

**Comment by zyoung51** [comment]
+1

**Comment by benbp** [comment]
@heckj or maybe just in the on-taskgraph README or even a README within lib/graphs that says "if you want to add a graph name it like this." In general I think keeping smaller documentation details within the repos like this is probably better, otherwise wouldn't we have a low signal to noise ratio in the readthedocs guide?

**Comment by heckj** [comment]
I'd be fine with a README addition, as long as we're consistent. I'd keep it top level, already seeing a pattern of people not looking for README's in subdirectories in https://github.com/rackhd/rackhd. Top level yeah, but stuff below seems to get quickly missed

**Comment by benbp** [comment]
Ok I'll add that to this PR.

**Comment by zyoung51** [comment]
@benbp a comment or logger.info about the globbing here might be cool too: https://github.com/RackHD/on-taskgraph/blob/master/lib/loader.js#L71

**Comment by anhou** [comment]
+1

**Comment by benbp** [comment]
Makes sense @zyoung51 I'll also add that in to this PR.

**Comment by benbp** [comment]
@heckj @zyoung51 updated for your comments. Added a README entry, JSDoc comments to the loader file, and updated the logger statements.

**Comment by heckj** [comment]
Thanks, :+1:

**Pull request merged**
