### PR TITLE
Add node tagging tasks to graphs

### PR DESCRIPTION
**Pull request by zyoung51**
@RackHD/corecommitters @uppalk1 @keedya @tannoa2 
Depends on https://github.com/RackHD/on-tasks/pull/124, https://github.com/RackHD/on-core/pull/88

### CODE REVIEW

**Comment by heckj** [comment]
question - is it worth adding this task into the switch or pdu discovery graphs as well as the compute ones?

**Comment by zyoung51** [comment]
@heckj That's a great question.  I do not have an answer or opinion on it.  
The tags do attempt to apply to all nodes, regardless of type, but the rules should restrict it to a node type by the catalog name.  I'll kick off a thread in google groups on it?

**Comment by heckj** [comment]
yeah, sounds good. Seems like it would be good to keep it consistent across all the kinds of nodes we support (`compute`, `switch`, & `pdu`) but the only concrete use case we have today is on `compute` - the largest of the herds of machines we'll manage

**Comment by jlongever** [comment]
test this please

**Comment by jlongever** [comment]
test this please

**Comment by jlongever** [comment]
test this please

**Comment by jlongever** [comment]
test this please

**Comment by jlongever** [comment]
+1

**Comment by brianparry** [comment]
:+1:

**Pull request merged**
