### PR TITLE
Pass an array of nodeIds to generate-tag task instead of a single nodeId

### PR DESCRIPTION
**Pull request by benbp**
Requires https://github.com/RackHD/on-tasks/pull/320 and https://github.com/RackHD/on-http/pull/442 (interdependent).

@RackHD/corecommitters @heckj @pscharla

### CODE REVIEW

**Comment by yyscamper** [comment]
:+1:

**Comment by anhou** [comment]
👍

**Comment by benbp** [comment]
test this please

**Comment by benbp** [comment]
@yyscamper re: https://github.com/RackHD/on-tasks/pull/320#issuecomment-242571058 it actually turns out that we _do_ use the convenient `nodeId` option sharing in many of our pre-existing graphs, so my concerns weren't actually hypothetical. I've updated all the graphs running the generate tag task to look like so in their options definitions:

```
    options: {
        defaults: {
            graphOptions: {
                target: null
            },
            nodeId: null,
            nodeIds: [ "{{ options.nodeId }}" ]
        }
    }
```

**Comment by changev** [comment]
jenkins: depends on https://github.com/RackHD/on-tasks/pull/320 https://github.com/RackHD/on-http/pull/442
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by pscharla** [comment]
@RackHD/corecommitters I got confirmation from @panpan0000 that we can ignore the Jenkins Dependency PR check for now. I think this is ready to merge.

**Pull request merged**
