### PR TITLE
Updates for Promise returning Task.create method. Fix asynchronous te…

### PR DESCRIPTION
**Pull request by benbp**
…sts.

Requires https://github.com/RackHD/on-tasks/pull/238

@RackHD/corecommitters @VulpesArtificem @heckj

### CODE REVIEW

**Comment by yyscamper** [comment]
:+1:

**Comment by anhou** [comment]
:+1: test this please

**Comment by yyscamper** [comment]
jenkins: test this please

**Comment by benbp** [comment]
@yyscamper Jenkins will fail here because of the dependency on on-tasks. In fact Jenkins will fail on both the on-tasks PR and the on-core PR. I've verified locally with all changes synced but might be good to get a second person to affirm the results.

**Pull request merged**
