### PR TITLE
Implement progress feature 

### PR DESCRIPTION
**Pull request by pengz1**
Related PRs:
https://github.com/RackHD/on-tasks/pull/364, 
RackHD/on-core#221, 
https://github.com/RackHD/on-http/pull/507
Add progress event trigger mechanism when task/workflow started/finished.

### CODE REVIEW

**Comment by rackhdmirror** [comment]
@RackHD/corecommitters please review.

**Comment by pengz1** [comment]
@RackHD/corecommitters @cgx027 @iceiilin @benbp @brianparry

**Comment by cgx027** [comment]
Looks good :+1:

**Comment by changev** [comment]
test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by changev** [comment]
test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by changev** [comment]
test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by brianparry** [comment]
@pengz1 This comment is really more for RackHD/on-core#221 which has already been merged, but could you explain why progress is being persisted?  It seems like progress is transient by definition.

**Comment by pengz1** [comment]
@brianparry 
Progress should be accessed via both AMQP message and RESET API. So it varies with time but should be able to be accessed (by API) at any time.

**Comment by brianparry** [comment]
@pengz1 In that case, why not have on-http subscribe to progress alerts and use those to render progress into the API?

**Comment by pengz1** [comment]
@brianparry 
Since progress is a feature for only active workflows/tasks, get this feature from active workflow will be more clear and straightforward. So I didn't create a new API but to add this attribute to current workflow/tasks models.

**Comment by pengz1** [comment]
@brianparry 
Are you worry about frequently updating of taskgraph/task data will lead to heavy loading of database operating? Progress is designed mainly for long-run task, progress update in my scope is updated in minutes (Secure erase is 1 minutes) and should not lead to heavy load on database. Another benefit we can see is that we can have HA feature if we keep it on disk instead of memory, so that we can know what happend in our last failed workflow after long-time running.

**Comment by brianparry** [comment]
@pengz1 My concern is not so much the load on the database but the fact that progress is meaningless across reboots so there is really no reason to persist it.

**Comment by yyscamper** [comment]
jenkins: test this please

**Comment by yyscamper** [comment]
Communicated with @brianparry in slack channel, he agreed to merge as it is. We will have some follow-up discussion about how to improve the progress reporting.

**Pull request merged**
