### PR TITLE
Add new graph to run a UEFI application (if compute is running in UEFI)

### PR DESCRIPTION
**Pull request by keedya**
depends on : https://github.com/RackHD/on-http/pull/201
depends on : https://github.com/RackHD/on-tasks/pull/152

### CODE REVIEW

**Comment by keedya** [comment]
@RackHD/corecommitters @tannoa2 @uppalk1 @zyoung51

**Comment by benbp** [comment]
:+1:

**Comment by yyscamper** [comment]
:+1:

**Comment by zyoung51** [comment]
+1

**Pull request merged**
