### PR TITLE
changed decommission graph to use sgdisk

### PR DESCRIPTION
**Pull request by DavidjohnBlodgett**
@RackHD/corecommitters 

this resolves https://github.com/RackHD/RackHD/issues/373

this depends on https://github.com/RackHD/on-imagebuilder/pull/56

### CODE REVIEW

**Comment by heckj** [comment]
👍

**Comment by yyscamper** [comment]
:+1:

**Comment by PengTian0** [comment]
test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by DavidjohnBlodgett** [comment]
please don't merge this yet

**Comment by PengTian0** [comment]
test this please

**Comment by PengTian0** [comment]
test this please

**Comment by PengTian0** [comment]
test this please

**Comment by tldavies** [comment]
test this please

**Comment by tldavies** [comment]
👍  when it passes Jenkins

**Comment by DavidjohnBlodgett** [comment]
Jenkins failure appears to be a result of my tests being in que for to long and timed out... http://rackhdci.lss.emc.com/job/Templates/job/downstream-trigger/228/

**Comment by tldavies** [comment]
test this please

**Comment by anhou** [comment]
Jenkins: depends on RackHD/on-imagebuilder#56

**Comment by anhou** [comment]
test this please

**Comment by anhou** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Pull request merged**
