### PR TITLE
Replace completionUri with notification

### PR DESCRIPTION
**Pull request by lanchongyizu**
* replace WaitCompletionUri with WaitNotificationJob in all workflows

** Note: Graph.Run.Emc.Diag can not complete now.

### CODE REVIEW

**Comment by rackhdmirror** [comment]
@RackHD/corecommitters please review.

**Comment by lanchongyizu** [comment]
@RackHD/corecommitters @zyoung51 @cgx027 @uppalk1

**Comment by iceiilin** [comment]
:+1:

**Comment by cgx027** [comment]
Looks great. :+1: 
Would you please create a follow up story to fix Graph.Run.Emc.Diag task, and assign to relative owner.

**Comment by uppalk1** [comment]
@lanchongyizu Were you able to test the Windows OS install workflow with min payload and full payload?

**Comment by lanchongyizu** [comment]
@uppalk1 I have tested it with a payload which should be aligned with min and full payload.

**Comment by yyscamper** [comment]
:+1:

**Pull request merged**
