### PR TITLE
Add switch/cisco switch discovery graphs

### PR DESCRIPTION
**Pull request by benbp**
This PR is one of a few changesets that add functionality for active discovery and configuration of network switches during their bootstrap processes (Cisco POAP, Arista ZTP, etc.). 

I am adding a bundle of what are intended to be RackHD built-in graphs (switch-active-discovery-sku-graph.js and switch-discovery-post-sku-hooks-graph.js) along with some example graphs for cisco cataloging and startup configuration (cisco-switch-discovery-graph.js and deploy-cisco-nexus3000-switch-startup-config-graph.js).

I'll put up a docs PR tomorrow, but the intent of these scripts is that the main switch active discovery graph calls multiple vendor specific sub-graphs. First the cataloging, the implementation of which varies vendor to vendor, and second any SKU-specific graphs that should be run. This is where you do things like specify deploying a startup config and potentially boot images. For example, here's an example SKU definition that can pair with these graphs for Cisco discovery:

```
{
  "name": "Cisco Nexus 3000 Switch - 54 port",
  "rules": [
    {
      "path": "version.chassis_id",
      "regex": "Nexus\\s\\d\\d\\d\\d\\w?\\sChassis"
    },
    {
      "path": "version.module_id",
      "equals": "48x10GT + 6x40G Supervisor"
    }
  ],
  "discoveryGraphName": "Graph.Switch.CiscoNexus3000.DeployStartupConfig",
  "discoveryGraphOptions": {
      "deploy-startup-config": {
          "startupConfig": "example-cisco-startup-config"
      }
  }
}
```

Requires:
https://github.com/RackHD/on-tasks/pull/158

Supports:
https://github.com/RackHD/on-http/pull/210
https://github.com/RackHD/on-dhcp-proxy/pull/32
https://github.com/RackHD/on-skupack/pull/10

FYI @dpasupathi

@RackHD/corecommitters @zyoung51 @heckj @pscharla @VulpesArtificem @johren

### CODE REVIEW

**Comment by benbp** [comment]
Tests are failing because this requires the minor change to the shell-reboot task requiredProperties in https://github.com/RackHD/on-tasks/pull/158. That PR can be merged independently of this.

**Comment by yyscamper** [comment]
test this please

**Comment by benbp** [comment]
test this please

**Comment by jlongever** [comment]
test this please

**Comment by heckj** [comment]
👍

**Pull request merged**
