### PR TITLE
Node discovered alert

### PR DESCRIPTION
**Pull request by anhou**
one part of spec https://github.com/RackHD/RackHD/wiki/proposal-AMQP-notifications-on-node-discovery-or-inaccessibility, node remove and inaccessible alert will be in a following PR

depends on PRs: https://github.com/RackHD/on-core/pull/159 and https://github.com/RackHD/on-tasks/pull/240

@RackHD/corecommitters @WangWinson @iceiilin

### CODE REVIEW

**Comment by anhou** [comment]
travisci fail due to dependency on https://github.com/RackHD/on-tasks/pull/240

**Comment by iceiilin** [comment]
:+1:

**Comment by yyscamper** [comment]
jenkins: test this please

**Comment by benbp** [comment]
:+1:

**Pull request merged**
