### PR TITLE
Add workflow for getting bios and update firmware

### PR DESCRIPTION
**Pull request by sunnyqianzhang**
With Racadm tool
This code review is link with the code change on on-tasks:
RackHD/on-tasks#133

### CODE REVIEW

**Comment by benbp** [comment]
:+1: 

Will you link the other PR in the description here so it's easier for us to know when it's ready to be merged? Thanks!

**Comment by anhou** [comment]
:+1: as @benbp mentioned, please help reference related PRs, it will help for PR's code review and merge

**Comment by sunnyqianzhang** [comment]
This code review is link with the code change on on-tasks:
https://github.com/RackHD/on-tasks/pull/133

**Comment by yyscamper** [comment]
:+1:

**Comment by yyscamper** [comment]
test this please

**Pull request merged**
