### PR TITLE
Add drive id catalog task in discovery workflow

### PR DESCRIPTION
**Pull request by pengz1**
Add drive ID catalog task in discovery workflow.

### CODE REVIEW

**Comment by pengz1** [comment]
@RackHD/corecommitters @linlynn @WangWinson

**Comment by WangWinson** [comment]
Looks like this PR has dependency on on-tasks to add ```Task.Catalog.Drive.Id```

**Comment by pengz1** [comment]
Task PR is in below link:
https://github.com/RackHD/on-tasks/pull/81

**Comment by yyscamper** [comment]
:+1:

**Pull request merged**
