### PR TITLE
Scheduler: call taskProtocol.cancel with timeout error/message on timout

### PR DESCRIPTION
**Pull request by johren**
Recreated PRs for ODR-273 fix on 1.0.0 branch.  Needed for 1.0.5 release.

### CODE REVIEW

**Comment by johren** [comment]
@benbp @yyscamper @anhou Please review to make sure I recreated this correctly.  

Please DO NOT MERGE until testing is complete.  Thanks!

**Comment by benbp** [comment]
:+1:

**Comment by johren** [comment]
Looks like @yyscamper approved the other two but missed this one.  We need to get this in today for 1.0.5.  Adding @VulpesArtificem as another set of eyes on this one.

**Comment by derrickostertag** [comment]
+1

**Comment by johren** [comment]
Testing was successful.  @benbp @yyscamper @anhou @brianparry or @jlongever, please merge these three PRs at the same time as soon as possible:
https://github.com/RackHD/on-tasks/pull/84
https://github.com/RackHD/on-core/pull/40
https://github.com/RackHD/on-taskgraph/pull/35

Thanks!

**Comment by yyscamper** [comment]
:+1:

**Pull request merged**
