### PR TITLE
Add Redfish catalog of dell endpoint to redfish discovery graph

### PR DESCRIPTION
**Pull request by srinia6**
Signed-off-by: Billy Abildgaard <william.abildgaardjr@emc.com>

Add Redfish catalog of dell endpoint to redfish discovery graph. Depends on 
https://github.com/RackHD/on-tasks/pull/462

### CODE REVIEW

**Comment by srinia6** [comment]
jenkins: depends on https://github.com/RackHD/on-tasks/pull/462

**Comment by BillyAbildgaard** [comment]
jenkins, test this please

**Comment by srinia6** [comment]
Test this please

**Comment by srinia6** [comment]
test this please

**Pull request merged**
