### PR TITLE
Remove unecessary graphId info for progress

### PR DESCRIPTION
**Pull request by pengz1**
Jenkins depends on: https://github.com/RackHD/on-core/pull/227, https://github.com/RackHD/on-http/pull/523, https://github.com/RackHD/on-core/pull/227, https://github.com/RackHD/on-tasks/pull/370
This PR is to remove unecessary graphId in task start/finish progress event.

### CODE REVIEW

**Comment by pengz1** [comment]
@RackHD/corecommitters @cgx027 @iceiilin

**Comment by anhou** [comment]
@pengz1 Any background for this?

**Comment by pengz1** [comment]
@anhou GraphId is already includes in progress info, I used to included graphId in taskProgress data because when we call store.updateTaskProgress, graphId is required inside this method. Later I changed store.updateTaskProgress parameter list form (data) to (data, graphId) so that we don't have to include graphId inside data. After this change, graphId is redundant in taskProgress (which is the real "data" that be delivered to store.updateTaskProgress).

**Comment by cgx027** [comment]
:+1:

**Pull request merged**
